### ISSUE TITLE
Import of data with version 1.5.0 not working anymore

### ISSUE THREAD

**Issue by Chedera** [Razviar/mtga-pro-tracker#185] opened 2018-11-21 21:11 UTC
The app does not import anything anymore for me. Before the update to 1.5.0 all was working well.
The app itself seems ok. Only the upload to the data server does not work.

I tried the scan old logs function, the resync function and then the tokens reset function but i could not get it to work again.

**Comment by AxDSan** [comment] 2018-11-21 21:19
Possible duplicate of #183

**Comment by Chedera** [comment] 2018-11-22 07:08
Clearing the directory worked perfect. Thank you very much.

**Comment by Chedera** [comment] 2018-11-22 07:10
Done :-)

**Closed** 2018-11-22 07:10 UTC
