### ISSUE TITLE
Error reading log and cannot change date format

### ISSUE THREAD

**Issue by nbelley** [Razviar/mtga-pro-tracker#462] opened 2019-07-24 22:12 UTC
So, I cannot change the date format, always says error on the bottom:

When I try to read log, I get an Error Reading Log

[date error](https://imgur.com/kpQzGlt)

**Comment by Razviar** [comment] 2019-07-25 08:22
You have an error in you data format input. In your date sample month comes first, so it will be:

M/d/yyyy h:mm:ss tt

**Comment by JohnMartincic** [comment] 2019-07-25 16:11
I am having a similar issue. As seen by the link at the bottom of my post it will tell me my Date format is correct, but after clicking save the main tracker window will say that I need to set the date format in settings again. If I got back to the settings page it still says that my date setting is correct. I am running version 1.7.9. This just randomly broke today, I have had it running for quite some time before this.

Link to images: https://imgur.com/a/aEUPC7V

**Comment by Kirsan13** [comment] 2019-07-25 16:47
Same problem as JohnMartincic.
And my link to img: https://imgur.com/a/0OdgrWh

**Comment by ArmanIzad** [comment] 2019-07-25 16:49
Same problem. I think the issue is with the log file, previously all the dates are separated by a newline

```[UnityCrossThreadLogger]7/26/2019 12:04:49 AM```

But since the new update that is not the case anymore

```[UnityCrossThreadLogger]7/26/2019 12:04:51 AM: Match to E46DE0EB02F9C80F: GreToClientEvent```

**Comment by SemtosSpielt** [comment] 2019-07-25 18:08
same here,

[UnityCrossThreadLogger]25.07.2019 19:37:39: Match to HNXHLI3WKJFZDCUKE3ZG7A7V6Y: GreToClientEvent

Format:  dd:MM:yyyy HH:mm:ss

**Comment by Le0nidass** [comment] 2019-07-25 18:22
Same here =(

**Comment by Razviar** [comment] 2019-07-25 20:25
This is global issue, fix will be delivered by evening of 26th Jul

**Comment by Razviar** [comment] 2019-07-26 20:04
https://github.com/Razviar/mtga-pro-tracker/releases/tag/1.8.0

**Comment by Razviar** [comment] 2019-07-27 09:29
Merged with https://github.com/Razviar/mtga-pro-tracker/issues/463

**Closed by Razviar** 2019-07-27 09:29 UTC
