### ISSUE TITLE
Wonky deck stats today.

### ISSUE THREAD

**Issue by YelmsLight** [Razviar/mtga-pro-tracker#243] opened 2018-12-28 15:54 UTC
I play to 15 wins a day, every day, unless I play in one of the constructed tournaments, which I did not do today, or if I'm testing a deck (which I did, but after I had noticed the issue).  My tracker shows me as having a record of 22-33 for a particular deck, which I had used exclusively, for the day.  There are several problems with that:  as I stated, I had only played to 15 wins.  Also, I wouldn't have had the time to play 55 games.  Finally, it's dragging down my win percentage.  I have a sense for these things, and I won more than I lost; there's no chance that I lost half again as many games as I won.  My estimate would be around 15-12 for the day.

The point is that that data is clearly wrong.  The first time I saw it it showed as something like 11-15 (which wouldn't have happened either, since I played all games entirely in one session, and it should have read 15 as the number of wins).  Then I reset the Tracker, and it jumped to the 22-33 number.  I tried resetting it again and there was no change from that number.  The readings are completely off for today.

I just reset the game again as I wrote this bug report, and it now reads 22-34 as the record?  Something is clearly wrong here.

**Comment by YelmsLight** [comment] 2018-12-28 15:57
Having reset the game again, the record has now advanced (declined?) to 22-35.

**Comment by YelmsLight** [comment] 2018-12-28 20:09
...and reset it again, so that it now reads 22-36.  All without having been in game.

**Comment by Razviar** [comment] 2018-12-29 18:17
We are updating tracking mechanism now, some weird stuff may happen

**Comment by 1MarkC** [comment] 2018-12-30 10:46
I also have weird behaviour. Tried manually updating logs many times to get my W:L ratio fixed, but it now shows I have 0:8, while it should be 2:4 (I think). 

My friends will laugh at me the whole day!

https://mtgarena.pro/u/1Mark  (shows 0:8)
https://mtgarena.pro/matches/#1Mark  (shows only 2 matches played, should be 5 or 6 matches, I think)

**Comment by iggraham** [comment] 2019-01-03 08:06
I can confirm that the deck stats are at least at little bit off pretty much every day for me, and as others have stated here and elsewhere the manual re-syncs and full resets just seem to compound the problem).  Mostly it seems to me like lots of matches are just missed.  And the manual re-sync just seems to add errant stats onto errant stats - one day with record of 1:3 became 2:6 and then 3:9 just from a couple re-sync attempts.

The primary value of MTGArena.PRO are these stats.  Please take a good hard look at getting their collection working correctly - this is much more important than adding any new features.

Just a small example below from my last few matches since midnight, where the deck stats are inconsistent with the ladder stats.  I'm not sure which is correct.
![mtgapro stats](https://user-images.githubusercontent.com/19194715/50628017-78521d80-0ef3-11e9-961e-69971a2ac7d1.png)

**Comment by Razviar** [comment] 2019-01-03 08:37
Issue now is localized, we are working on it.

**Comment by Razviar** [comment] 2019-01-03 10:40
Starting now the issue is fixed. Hopefully. 
Correct stats should appear starting the next day, Jan 04.
Not closing ticket yet, to make sure it's fixed.

**Comment by Razviar** [comment] 2019-01-03 20:01
Stats are fixed

**Closed by Razviar** 2019-01-03 20:01 UTC
