### ISSUE TITLE
Can't upload my stats from the app to the site

### ISSUE THREAD

**Issue by Manager7** [Razviar/mtga-pro-tracker#421] opened 2019-06-01 16:33 UTC
Hi...After 23rd of  May my stats and progress cant be uploaded to the site...I tried manual resynch and reading old logs but it doesn work...If i have the MTG Arena app open it stucks at awaiting update and if i dont have the MTG Arena app open it says tha it is not open...What can I do to upload my progresss again ?

**Comment by Razviar** [comment] 2019-06-03 03:18
Are you on latest tracker app version?
You should try full reset button in the app interface.

**Comment by Manager7** [comment] 2019-06-03 05:53
Yes I have the latest version and I did the full reset multiple times...I also uninstalled and installed again...I allowed the app through the firewall and the antivirus ,  i tried to scan every log and also did a manual resynch but nothing works

**Comment by Razviar** [comment] 2019-06-03 07:14
Okay, I need a link to your profile on site to be able to investigate anything.

**Comment by Manager7** [comment] 2019-06-03 09:08
https://mtgarena.pro/u/Manager

**Comment by Razviar** [comment] 2019-06-03 09:18
Thanks, we'll investigate

**Comment by khazidroid** [comment] 2019-06-03 14:17
I am having the same issue, since the recent May updates I am unable to upload any logs.

I do not see the app going through the upload log sequence, I have tried manual sync and several re-installs.

My profile page is : https://mtgarena.pro/u/khazi_droid

**Comment by Razviar** [comment] 2019-06-03 14:19
Did you attempted to use FULL RESET button with getting a new token?

пн, 3 июн. 2019 г., 17:17 khazidroid <notifications@github.com>:

**Comment by Mollerz** [comment] 2019-06-03 22:01
Same issue here. I played for about 4 hours today and completed two sealed drafts that became unlocked today. Seems to have bugged and not recorded correctly. It did record a "Draft Deck" that went 0-1 but it was not what was drafted and in fact I went 0-3 with this deck and 5-3 with another deck that has been completely omitted. My profile: https://mtgarena.pro/u/Mollerz/

**Comment by khazidroid** [comment] 2019-06-04 04:22
Razviar - thanks for your response.

I was hoping that I would not need to do a full reset as I do not want to lose all my recent history/progress if at all possible.

However if you think that a full reset will work then so be it.

Can you confirm please ?

**Comment by Razviar** [comment] 2019-06-04 04:24
Full reset does not remove any data from site. It just wipes locally stored data and helps app to get on track. So you can freely use full reset. And I probably should rename this button, because many people are afraid of it :)

**Comment by rev0lut** [comment] 2019-06-04 07:58
I have the same issue. I cannot upload my log since the latest update of MTGA.
My pro tracker goes "Launcing-resync"-"Reading log"-"Awaiting for updates" really fast and nothing happens, no upload.
This is my profile https://mtgarena.pro/u/revolut
I have downloaded the latest version of pro tracker. Re-installed it several times. Re-Installed even the game. Used manual re sync. Used full reset. Nothing...

Please help I find the tool powerful, and really enjoy it. I want to keep using it!!!

**Comment by Mollerz** [comment] 2019-06-04 08:08
Yeah I've used a full reset and it still isn't working. No changes to as it was before.

**Comment by Razviar** [comment] 2019-06-04 08:16
The problem is, I cant reproduce the issue, and that's why I have no idea why it's happening. For most of users it works fine. I tested myself, and it works. So it's complicated to understand why it's happening. 
Here's some things you can do to help me finding out what is wrong:
1. Check if game log is in place (it should be located here: C:\Users\{USERNAME}\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt )
2. If it is, send me zipped log. You can, for instance, upload it to some online file bucket and drop link over here.

**Comment by rev0lut** [comment] 2019-06-04 08:33
this is my log. I found it where you instructed.
[https://acgedu30684-my.sharepoint.com/:t:/g/personal/d_kalogeras_acg_edu/EXcEnd96CfJKlS_7-ZsORYEBKRaXywZObMc1bfrSvv6MGQ?e=ieFPsr](url)

**Comment by Razviar** [comment] 2019-06-04 08:44
You must be from Greece :) Since instead of P.M. it's "π.μ" in time marking. Tracker got confused with this mysterious symbols from ancient alphabet and stuck, lol. Working on the patch now, which will provide better time formats handling. Probably we will even collect time formats and make universal solution for all cultures.

**Comment by Razviar** [comment] 2019-06-04 09:15
Here you go, everyone who has this issue should update to 1.7.0 and use Full Reset button. 
If you are from Greece, it will resolve you problem immediately. 
If not, you will help to collect needed data and your time format will be added in the next release. We will wait some time until we'll be able to gather more, so with 1.7.1 most of the exotic time formats will be handled.

**Comment by rev0lut** [comment] 2019-06-04 09:23
Yes ancient symbols 😁
Much respect for you!!! Thank you millions.
Thank you kind friend!

**Comment by Mollerz** [comment] 2019-06-04 10:43
I'm from the UK so I would have assumed that it would have all been fine for me... Although I do use the Korean keyboard so sometimes when I set up things it thinks I am Korean. Once I'm home from work I will update, try the usual and if no luck will send my logs in.

**Comment by khazidroid** [comment] 2019-06-04 15:46
Razviar - I am in eastern Australia - Sydney, we are GMT + 10 right now.

Tried the full reset but still no luck.

I have zipped the MTGA output log and dropped it here, hope thats ok.

[output_log.zip](https://github.com/Razviar/mtga-pro-tracker/files/3253290/output_log.zip)

**Comment by Mollerz** [comment] 2019-06-04 17:41
Still no luck here. Did a full uninstall of MTGAPro, full reset, etc. Here's my log

https://drive.google.com/file/d/1u7b1QicxutnZaGMLWM5ugVFji-UdEvkX/view?usp=sharing

**Comment by Razviar** [comment] 2019-06-04 17:47
v.1.7.1 is out, feel free to give it a try

**Comment by Razviar** [comment] 2019-06-04 18:14
Bad news for everyone who still has issues after v.1.7.1 - it means that problem was not the date format, and we'll still need to find out what's wrong. So, for now here's the plan:
1. Update to 1.7.1
2. Full Reset
3. Experimental match
4. Check of upload, if no luck - report here with log attached.

**Comment by Mollerz** [comment] 2019-06-04 19:34
Working for constructed at least for now, will have to update later in regards to sealed/draft working (which is where it didn't work before).

**Comment by Oredna** [comment] 2019-06-04 21:57
1 day behind, and I did everything, maybe wizards ar attempting something fishy ?

**Comment by GabbedAgain** [comment] 2019-06-04 23:17
Possibly unrelated but the dates also look to be mirroring reporting in the progress tracker... For example my collection stats are mirroring today's date with April 6th... (04/06/19 vs 06/04/19)...
[Screens
](https://imgur.com/a/ynH52LO)
Not sure if that's related to any other issues...

**Comment by RaiderAdam** [comment] 2019-06-05 01:03
Noticed issue yesterday where arena pro tracker loops multiple times saying game info found, reading logs, awaiting update.

Same today and upgraded to 1.7.1.  Same issue.  Did Full reset.  Closed program, reopened, readded token.  Told it to scan old log and same thing happened.

Attached is compressed output.log from C:\Users\adam\AppData\LocalLow\Wizards Of The Coast\MTGA
[output_log.zip](https://github.com/Razviar/mtga-pro-tracker/files/3255053/output_log.zip)

**Comment by RaiderAdam** [comment] 2019-06-05 01:06
Here is last log from here:
C:\Program Files (x86)\Wizards of the Coast\MTGA\MTGA_Data\Logs\Logs
[UTC_Log - 6-5-2019 12.25.12 AM - 1.htm.zip](https://github.com/Razviar/mtga-pro-tracker/files/3255056/UTC_Log.-.6-5-2019.12.25.12.AM.-.1.htm.zip)

**Comment by lemabr01** [comment] 2019-06-05 01:34
I also am having this issue. No logs have been uploaded since yesterday despite multiple sessions of logs. Uninstalled program, re-installed, did a full reset and nothing has happened.

**Comment by Razviar** [comment] 2019-06-05 04:53
Multiple loops of uploads is normal behavior, it's how it handles big logs.

We will add manual date format setup, since it's getting too messy. For instance, in some countries month goes first, in other day comes first, that is why day and month gets swapped. So we will have standard format by default and option to input your format in settings.

**Comment by lemabr01** [comment] 2019-06-05 05:00
Thanks!

Will this retroactively fix any uploaded data that was assigned to the wrong day or will we need to reupload those periods after a patch?

**Comment by Razviar** [comment] 2019-06-05 05:02
Unfortunately what have been written cannot be fixed, so it will start doing new records correctly. Actually, I'm already applying fix, no need to roll out new version

**Comment by lemabr01** [comment] 2019-06-05 05:08
Ah. Is there any way to delete the data on your own profile that was assigned the wrong day?

**Comment by Razviar** [comment] 2019-06-05 05:09
You can use this: https://mtgarena.pro/wipe/

**Comment by lemabr01** [comment] 2019-06-05 05:42
Fix appears to have worked. Opened 2 packs to test and both appeared on the proper date. Thank you!
![Untitled](https://user-images.githubusercontent.com/25397001/58932829-3bed4c80-8733-11e9-840c-4b76df61efc8.png)

**Comment by Jonius7** [comment] 2019-06-05 11:50
Mine seems to be showing the day and month inverted. i.e stats from 5 June are shown as May 06, which would explain where everything since May 31 has gone. Unfortunately I did the wipe, but I imported the logs from June 2 back in.

**Comment by nsmvjher** [comment] 2019-06-05 12:03
i opened the app and shows :troubles with upload

**Comment by Razviar** [comment] 2019-06-05 13:29
v.1.7.2 is out, with comprehensive solution to all date format issues.

**Comment by RaiderAdam** [comment] 2019-06-05 14:03
> Multiple loops of uploads is normal behavior, it's how it handles big logs.
> 

Except I have never seen it behave that way before.  Normally it processes, several seconds to upload and then go again.  In this, it is literally like half a second looping between steps.

**Comment by khazidroid** [comment] 2019-06-05 15:28
Razviar - looks like it worked for me - at least for the one game as instructed after update to 1.7.1, full reset, and play one match.

Let me know if you want the output log if it is of any use for you.

Will let you know how I go tomorrow with more games :)

**Comment by Razviar** [comment] 2019-06-05 22:06
Please update to v. 1.7.3 to get latest patches. Also, users with nonstandard time formats should input time formats settings according to manual (see link in settings window)

**Comment by Razviar** [comment] 2019-06-07 10:21
Seems to be resolved, closing this now.

**Closed by Razviar** 2019-06-07 10:21 UTC

**Comment by lucatrincauk** [comment] 2019-06-07 18:58
Still happening for me. v1.7.5, did a full reset a few times.

Time in the logs is like this: 25/06/2019 18:59:39

I set it in the settings like this: dd/MM/yyyy HH:mm:ss

It says Date is correctly set but it keeps going in loop between reading log and game info found.

[output_log.zip](https://github.com/Razviar/mtga-pro-tracker/files/3267244/output_log.zip)

**Comment by Razviar** [comment] 2019-06-07 19:03
Loop you described is normal. Just wait until it finishes and see if something uploaded on site

**Comment by lucatrincauk** [comment] 2019-06-07 20:21
hm ok, thanks.

some data is updated but some is not. for example, last booster opened is dated Mid May, which is not true. I checked some cards redeemed recently and they show in the rewards list but not in my collection.

I'll leave it running and give it some time to go through the whole log, since it's quite big, maybe it's that.

**Comment by Mollerz** [comment] 2019-06-07 21:45
Deck is not getting captured in the temporary mode: mtga.cc/u/Mollerz

**Comment by Chrisplays** [comment] 2019-06-12 20:12
Here is the link to the my profile as requested on twitter: https://mtgarena.pro/u/Chrisplays/




[UTC_Log - 6-12-2019 10.49.02 AM - 1.htm.zip](https://github.com/Razviar/mtga-pro-tracker/files/3282991/UTC_Log.-.6-12-2019.10.49.02.AM.-.1.htm.zip)
